version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: kotobalog_db
      MYSQL_ROOT_PASSWORD: EUMS9pbJwcVB7AS7gBRCUvfm
    volumes:
        # 永続化するときにマウントするdir
        - ./db:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: web
    command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb -E ${RAILS_ENV}
    environment:
      RAILS_ENV: ${RAILS_ENV}
      APP_DATABASE_PASSWORD: ${APP_DATABASE_PASSWORD}
    volumes:
      - /share
      - ./web:/app
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - db

  vue:
    build: vue
    volumes:
      - ./vue:/www
    ports:
      - "127.0.0.1:8901:8080"    
    tty: true

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./vue/dist:/www
      - ./web/static:/assets
    links:
      - web
    ports:
      - "${NGINX_PORT:-8900}:80"
    environment:
      TZ: "Asia/Tokyo"