version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    build: web
    command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb
    volumes:
      - /share
      - ./web:/app
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - db

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/static:/static
    links:
      - web
    ports:
      - "${NGINX_PORT:-8900}:80"
    environment:
      TZ: "Asia/Tokyo"